### ISSUE TITLE
commit-messages report

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#11]
I ran the commit-messages task several times, with varying parameters as follows

```
gulp commit-message-analysis --dateFrom=2015-01-01 --dateTo=2017-12-31 --minWordcount=1
gulp commit-message-analysis --dateFrom=2015-01-01 --dateTo=2017-12-31 --minWordcount=5
gulp commit-message-analysis --dateFrom=2015-01-01 --dateTo=2017-12-31
```
The reports view always shows `minWordCount=5` in the reports list and `Word occurency 5` for the view itself.

**Comment by smontanari** [comment]
the parameter name is case sensitive. It looks like you pass "minWordcount" instead of "minWordCount"
