### ISSUE TITLE
typos?

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#15]
In the wiki, under developer effort analysis, I noticed the sentence "One of the biggest challenges of any scaling ..." - typo on "any"?

on page coupling analysis I noticed the following paragraph

The resulting report is a list of files/modules that are potentially coupled with the original file. The coupling degree between two files is determined based on the number of shared commits within the given period.

Type on "determined based"

**Comment by smontanari** [comment]
thanks, I'll review and amend
