### ISSUE TITLE
code ownership blank

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#18]
I am still using alfresco-repository as repo and main-dev-coupling-data.json remains empty although code-ownership-report.json has 4000+ entries for the range 2017-06-01 to 2017-11-01.
Under what conditions would a 'code ownership' result in no data?
TIA

**Comment by smontanari** [comment]
There are several code-maat command line options that determine the granularity of the analysis. The options `-m` and `-n` in particular can drastically change the result of the analysis. My suggestion is to run the analysis in debug mode (setting the env variable COMMAND_DEBUG) and detect the code-maat command that is used to extract the coupling data, then execute that command yourself to see what the output is and maybe play with the code-maat options to see if you can fetch better/different results. If you find a set of options that returns meaningful data then you can add them to code-forensics either through the command line or through the `.code-forensics` configuration file.

**Comment by jdevoo** [comment]
Thank you Silvio - lowering `m` and `n` to 4 yielded the graph below.
Any specific reason for not using the radial layout with splines?

![coupling-analysis](https://user-images.githubusercontent.com/16983/33421649-0cfcc654-d5b3-11e7-8c7d-8e2e298205c1.png)

**Comment by smontanari** [comment]
The bubble chart gives me the ability to size the circles based on the number of authors and tune the colour based on the number of revisions, which helps to highlight the files with higher churn and more contributors, where coupling issues may represent bigger risks. I wasn't sure how to tweak the spline chart to achieve a similar outcome.

**Comment by jdevoo** [comment]
Thank you again Silvio!!!
