### ISSUE TITLE
Typos (wiki-pages)

### ISSUE THREAD

**Issue by andife** [smontanari/code-forensics#2]
I found some minor error in the wiki 
(but I was not able to fork the wiki to commit changes)

**Home.md**

1) In order to to fully  => In order to fully 
2) I highly recommended => I highly recommend
3)  - [**Developer coupling and communication**](Developer-coupling-analysis): chapter 12 and 15
=>  - [**Developer coupling and communication**](Developer-coupling-analysis): chapters 12 and 15
4) the availabe analysis: -> the available analysis:

**Advanced-setup.md**

1) several  errors => several errors (one space too much)

2) JavaScript AST (Abstract Syntx Tree). => JavaScript AST (Abstract Syntax Tree)

3) **code-foreniscs** to use a different jar file for _Code Maat_ if => 
 **code-forensics** to use a different jar file for _Code Maat_ if
 
 
**Developer-effort-analysis.md**
 
1) aggreagated => aggregated
a) data is also aggreagated at team level.
b) same data is also aggreagated at team level.

2) representation is particulary useful  => representation is particular**l**y useful 

3) nodes by on ly showing  => nodes by only showing 

**Developer-coupling-analysis.md**
1) may cause a certaing degree of coupling 
=> may cause a certain degree of coupling  

**Configuration.md**
1) their  aliases under  => their aliases under (space to much)

**Comment by smontanari** [comment]
Typos fixed, thank you @andife for taking the time to read through all the pages and notifying me.
