### ISSUE TITLE
Blank gulpfile.js with repository info not enough to run tasks

### ISSUE THREAD

**Issue by doytsujin** [smontanari/code-forensics#23]
Blank gulpfile with only repository information does not work. Because gulpfile needs tasks specified, otherwise without tasks, nothing will work. Gulp will return error about default task not in gulpfile. Does core-forensics package includes actual tasks? Why tasks are not visible for gulp to execute with minimal gulpfile?

**Comment by smontanari** [comment]
@doytsujin please take the time to read the documentation. It clearly explains how to configure and run the program.
code-forensics dynamically defines all the tasks necessary for gulp to run. A default task is also defined and is the `help` task, which lists all the available commands/tasks you can run.

If your gulpfile only contains a reference to your repository you should still be able to execute just gulp and see the list of available tasks. If that doesn't happen there must be something wrong in the way you have installed code-forensics. What is the command you're executing and what is the output?

**Comment by doytsujin** [comment]
Sorry for confusion. I tried Docker image instead and it worked. Thanks for the great project. Will consider to contribute!
