### ISSUE TITLE
gulp-util deprecation warning upon install...

### ISSUE THREAD

**Issue by gernotstarke** [smontanari/code-forensics#24]
I get the following warning/error upon install:

`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`

with a brief look I didn't find any explicit reference of gulp-util - therefore I'm lacking any idea how to fix this issues...

**Comment by smontanari** [comment]
At some point I'm going to upgrade to `gulp 4` and that should remove the need of `gulp-util`, 
 `graceful-fs` and possibly other deprecated dependencies

**Comment by smontanari** [comment]
latest version uses gulp 4 now
