### ISSUE TITLE
File supported

### ISSUE THREAD

**Issue by hsendoa** [smontanari/code-forensics#28]
Hi, what's the supported files?
Exists some plugin for sql suport?

**Comment by smontanari** [comment]
Some analyses (e.g. coupling, ownership) will work with any file type. More code specific analyses (e.g. sloc, complexity) will depend on the programming language.

- Complexity metrics can be captured for `ruby` and `javascript` only. I welcome anyone willing to add new complexity analysers for other programming languages.
- Sloc (source lines of code) analysis is based on the npm package `sloc` which supports a bunch of languages ([see here](https://github.com/flosse/sloc#supported-languages)). Such list unfortunately does not include sql, however you could always contribute to that project by [adding a new formatter](https://github.com/flosse/sloc#contribute-an-new-formatter). Also documented [here](https://github.com/flosse/sloc/issues/87).
