### ISSUE TITLE
Respect .mailmap file when analysing git repo

### ISSUE THREAD

**Issue by nlochschmidt** [smontanari/code-forensics#61]
We are using a [`.mailmap` file][1] to fix wrong names and merge commits from the same user. Sadly, the `.mailmap` file is currently being ignored by code-forensics. 

I think all it takes is to change the git log command from using [`%an` to `%aN`][2]:

> %an author name
> %aN author name (respecting .mailmap, ...)

Any reason not to use this?

[1]: https://github.com/git/git/blob/master/Documentation/mailmap.txt
[2]: https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emanem

**Comment by smontanari** [comment]
No, not really, other than using `.mailmap` doesn't seem to be a popular practice, and, in my experience, most repos just don't have it, or if they do it is not maintained properly. 
However, as you suggested, the change should be trivial as well as harmless with respect to the current functionality, and it will benefit teams (especially large ones) where effort and discipline had been put into maintaining such file.
I'll get it in soon and close this issue when it's done

**Comment by smontanari** [comment]
@nlochschmidt I have published release `2.4.0`, which, amongst other things, updates the git log command to respect the `.mailmap` file. 
I'm going to close this issue, but if you still have problems with the author log information please create a new one.

**Comment by nlochschmidt** [comment]
Much appreciated. Thank you!
