### ISSUE TITLE
window.System.config is not a function" error when accessing http://localhost:3000/index.html

### ISSUE THREAD

**Issue by thealexandrelara** [smontanari/code-forensics#65]
I'm getting an error on console when I execute webserver and I try to access http://localhost:3000/index.html

![image](https://user-images.githubusercontent.com/20469356/108633752-c66c6700-7454-11eb-9ce2-706afa0865c1.png)

![image](https://user-images.githubusercontent.com/20469356/108633790-02073100-7455-11eb-8cdb-2171be0b2618.png)

My gulp version is the following:
```
CLI version: 2.3.0
Local version: 4.0.2
```

My gulpfile.js was configured with the minimal configuration:
```
require('code-forensics').configure(
  {
    repository: {
      rootPath: "./src",
    }
  }
)
```

**Comment by smontanari** [comment]
repeated in #66
