### ISSUE TITLE
Forcing visualisation of developer effort analysis to always use colors

### ISSUE THREAD

**Issue by ghost** [smontanari/code-forensics#68]
Basically if you have in project a lot of different paths with different lengths like for example:
- a/b/c/d
- a/b/c/e
- a/b/c/f/g/h
- a/b/z

Then you gonna have (most of the time) a lot of gray color in visualization, which reduces usefulness of it.
![image](https://user-images.githubusercontent.com/79662385/114039036-af59cb00-9882-11eb-9c48-e97225fb90c6.png) (Gray like here.)

**Comment by smontanari** [comment]
>Then you gonna have (most of the time) a lot of gray color in visualization, which reduces usefulness of it.

That ultimately depends on what _useful_ means to you. 

When analysing file metrics I generally use _enclosure_ diagrams or, like in this case, a _tree map_ diagram. The reason being that we normally structure our files in a hierarchical fashion (a directory tree) and those diagrams make it easier to navigate a large codebase with hundreds or thousands of files. To be clear, the intent is not to render metrics at an aggregate level.

The purpose of this graph, in particular, is to represent the ownership/effort distribution on each file of the codebase, or, if you want, its level of fragmentation. Note that I explicitly stated _each file_, whereas, if I interpret correctly your demand, you're asking to have a representation at _directory_ or _folder_, _module_ level.

While in principle I can see the reason behind that, I would argue that its value depends mostly on how you _logically_ structure your codebase. And that can vary depending on many factors that have little to do with what this analysis is about, such as:
- language frameworks conventions (e.g. think Ruby on Rails vs a React app)
- architectural conventions (e.g. having a _frontend_ or _database_ folder) 
- your organisational structure (think _Conway's law_)

While a fragmentation at file level has a well known meaning and there are _best practices_ principles that can help you understand when fragmentation is good or bad in a file, as soon as you move up the directory tree, that meaning becomes completely dependent on your particular choices on how you organised your project files.
Moreover, if you have a large number of developers, the chance is that the higher up you go in the directory tree from the file level view, the more cluttered the representation becomes (basically a large mosaic of colours) and the less useful its information, to the point of being completely irrelevant (think for example the root directory of your codebase).

For those reasons, at the moment I'd be a bit reluctant to add this feature, but if many more users were asking for it I would definitely look at what it would imply as far as implementation goes.
