### ISSUE TITLE
Generate html files instead of using a webserver

### ISSUE THREAD

**Issue by joneshf** [smontanari/code-forensics#7]
This is amazing! Thanks for your work putting this together!

Is there an easy way to generate html files as the output instead of running a webserver? I'd love to use this in places where servers can't run (GH pages, AWS S3, etc). Basically, any place where you can host css/html/js files, but can't have a server running.

**Comment by smontanari** [comment]
The app content is mostly dynamically generated and what you see on the browser is not the actual content of the http response. You can save the full page through your browser and that will allow you to view a graph directly from a file, but you won't be able to use any of the diagram selections or filtering options available. However, if your purpose is simply to store the data used to generate the graphs, you could still extract everything under the output folder to copy it later onto another laptop where code-forensics is installed.

**Comment by joneshf** [comment]
The problem is, I can't run code-forensics on these servers. AWS S3, for example, only allows hosting static files.

**Comment by smontanari** [comment]
I realise that, however you could generate the static files with your laptop and then upload them to S3. Then you can download those onto another laptop and open them in a browser. Obviously all the limitations I mentioned earlier still apply, but at least you don't necessarily need nodejs and code-forensics installed on the other laptop to see a graph. Other than that there is not much else you can do.
